ddl:
  migration:
    generate: true
    run: true

ebean:
  migration:
    run: true

datasource:
  db:
    username: sa
    password: ''
    databaseUrl: jdbc:h2:mem:regular
    databaseDriver: org.h2.Driver
